language: node_js

node_js:
  - 7

services:
  - docker

env:
  - APP_PORT=3000 DB_URI=mongodb://localhost:27017/super-enigma-db

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - make build-image image-publish IMAGE_VERSION=$TRAVIS_BRANCH

branches:
  only:
    - develop
    - tags
